language: java

addons:
  sonarcloud:
    organization: "nortthon-github"
    token: $SONAR_LOGIN

#after_success:
#  - ./mvnw sonar:sonar -Dsonar.projectKey=nortthon_safe-scheduling -Dsonar.organization=nortthon-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
