language: java

after_success:
  - ./mvnw sonar:sonar -Dsonar.projectKey=nortthon_safe-scheduling -Dsonar.organization=nortthon-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
