language: java
addons:
  sonarcloud:
    organization: nortthon-github
    token:
      secure: "FhULvg4VXnPJ7phhieFfmf3q6FOIDXnD/a1CdTbuzlqKAO61DPGthB/+Y7XOBv5p9U2sKo2q5MkUuEDGUAzLUP8r59kpwOotWKdW9dcNEOY4VTiFP1VJ0s1XFqu4+aGLl5/vqGoblOb4ZCF0T6RLEAfEf6KSLLj7aN4trfbXOVRVY+sICrGc9NexyLxpk7IqxyOmR0SC49Am5md8rf+wobmfk4pCS2TfEe4BKpEHG8ybf58QTdt8RYgeBuU6t9kBfNE3wtVHgACHtYEXmqaA41/7yatXLPrJoKdf6ulsbteEoLrU31jg6RExGl/0u6URVk+24YgxyIxYbOhRNltgD+xPOBtwkUgzrDdZEos2kmbB15qeXwF91CkqY1rL8pd98riCjWeFsH7B6mWE0j027pDnkpSgzMToZk6baHAM2uscG9NOiRzJRYhwy02WqIKyR6kn4+foFllr2LWuIDuR30dSATmW1ElYrljiVjFuNWfav1g8bBxTXLwQpE/QisTEQDCOd1vn+i7FVZXHFMC9xLVpmKVW2aTaWuy5O8tHbryAJi0H4++lMIK1PSknnn+Fs55x0uD0fww9vqg9lKH04jaaVEYkuD3/4LYYmwib9ACWHOuwJzP1x2PBiEYmEGeDDRv6JOWK4OfIxszN2RoxkBs8Rcl1S1f82rNZmUgv2Jo="

script:
- "./mvnw verify sonar:sonar"

