name: Pipeline Embedded Off
on:
  push:
    branches:
    - embedded-off

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:3.6
        ports:
          - 27017/tcp
        env:
          SPRING_DATA_MONGODB_URI: "mongodb://localhost:${{ job.services.mongo.ports['27017'] }}/dbSafeScheduling"
      redis:
        image: redis
        ports:
          - 6379:6379/tcp
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build App
      run: mvn package -DskipTests
    - name: Unit Test
      run: mvn test